window.davetiyeAyarlari = {
    "gelinAdi": "Zeynep",
    "damatAdi": "Alper",
    "gelinTamAdi": "Zeynep Tekin",
    "damatTamAdi": "Alper Kılıç",
    "gelinAilesi": "Gurbet & Aziz",
    "damatAilesi": "Ayten & Kadir",
    "sayacTarihi": "2026-06-29T20:00",
    "anaTarihMetni": "PAZARTESİ, 29 . 06 . 2026",
    "genelKonum": "GAZİEMİR, İZMİR",
    "kinaTarihi": "28 Ağustos 2026",
    "kinaSaati": "19:00",
    "kinaGunu": "CUMA",
    "kinaMekani": "DURAN EMMİ'NİN KIRAATHANESİ",
    "kinaAdresi": "Salacak Mah. Üsküdar/İstanbul",
    "kinaHarita": "https://goo.gl/maps/duran-emmi-ornek-link",
    "dugunTarihi": "29 Haziran 2026",
    "dugunSaati": "20:00",
    "dugunGunu": "PAZARTESİ",
    "dugunMekani": "BİZİM BAHÇE DÜĞÜN SALONU",
    "dugunAdresi": "Dokuz Eylül Mah. Akçay Cd. No:235 Gaziemir/Izmir",
    "dugunHarita": "https://maps.app.goo.gl/MGU47AGV2CgSneiT7?g_st=ac",
    "anaSoz": "Bir ömür sürecek hikayemizin başlangıcında sizleri de yanımızda görmekten mutluluk duyarız.",
    "diniSoz": "\"Ey oğul! Aşk nasip işidir, hesap işi değil... Kader gayrete aşıktır derler, biz gayret ettik nasibimizi bulduk.\"",
    "diniSozSahibi": "- Ömer Baba",
    "muzikYolu": "public/music/elif.mp3",
    "showOpening": true,
    "showKina": false,
    "showOmerBaba": false,
    "showRSVP": false,
    "galeriFotograflari": []
};